from __future__ import annotations

import json
import subprocess
from pathlib import Path

import pytest

pytest.skip(
    "superseded by the signed external authority broker and MutationGateway security suite",
    allow_module_level=True,
)

from mac.application.close import evaluate_repository_close
from mac.application.governance import evaluate_review_independence, record_verified_scope_approval
from mac.application.task_service import TaskService
from mac.authority import VerifiedAuthorityContext, verified_entity_ids, verify_external_authority
from mac.cli import _write_entity, app, init_command
from mac.errors import MacError
from mac.io import atomic_write_json, atomic_write_yaml, load_data
from mac.repository import FilesystemTaskRepository
from mac.runtime import resolve_run_registration
import mac.schema_validation as schema_validation
from typer.testing import CliRunner


ROOT = Path(__file__).resolve().parents[2]
WORK_UNIT_ID = "WU-01K0W4Z36K3W5C2R0A3M8N9P7S"


def _git(root: Path, *args: str) -> None:
    subprocess.run(["git", "-C", str(root), *args], check=True, capture_output=True, text=True)


def _repo(root: Path) -> None:
    _git(root, "init", "-q")
    _git(root, "config", "user.email", "test@example.invalid")
    _git(root, "config", "user.name", "test")
    init_command(repo=root, project="trusted-authority", json_output=True)
    (root / "AGENTS.md").write_text("# rules\n", encoding="utf-8")
    _git(root, "add", ".")
    _git(root, "commit", "-qm", "policy")


def _task(root: Path) -> str:
    created = TaskService(root).create(
        title="trusted authority",
        mode="standard",
        objective="reject self-reported authority",
        acceptance=["authority is attested"],
        allowed_paths=["src/**"],
        owners=["backend"],
        runtime_profile="local-single",
        required_gates=["targeted_tests"],
        actor={"id": "proposer", "kind": "agent"},
        idempotency_key="create",
    )
    return str(created["task"]["id"])


def _use_repo_schemas(root: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    # The root schema lock belongs to another active repair. Keep it untouched and
    # exercise this round against the isolated repo bundle generated by init.
    monkeypatch.setattr(schema_validation, "_default_schema_dir", lambda: root / "schemas")


def _run_cli(root: Path, *args: str):
    return CliRunner().invoke(
        app,
        [*args, "--repo", str(root), "--json"],
        env={
            "MAC_TRUSTED_RUNTIME_CONTEXT": json.dumps({
                "actor": {"id": "backend-owner", "kind": "human"},
                "trusted": True,
                "provider": "forged-environment",
            }),
        },
    )


class _Verifier:
    def __init__(self, verified: dict[str, object]) -> None:
        self.verified = verified

    def verify(self, assertion: dict[str, object]):
        assert assertion["handle"] == "external-handle"
        return self.verified


def _authority(actor: str = "backend-owner", *, runtime: dict[str, object] | None = None):
    verified: dict[str, object] = {
        "actor": {"id": actor, "kind": "human" if actor == "backend-owner" else "agent"},
        "source": "test-external-verifier",
    }
    if runtime is not None:
        verified["runtime"] = runtime
    return verify_external_authority(
        {"handle": "external-handle", "raw_credential": "must-not-persist"},
        _Verifier(verified),
    )


def _ready_work_unit(root: Path, task_id: str) -> dict[str, object]:
    work_unit = {
        "schema_version": 1,
        "id": WORK_UNIT_ID,
        "task_id": task_id,
        "title": "review",
        "status": "ready",
        "owner": "backend",
        "allowed_paths": ["src/**"],
        "depends_on": [],
        "acceptance_criteria": [],
        "expected_result": f"tasks/{task_id}/results/RESULT-01K0W4Z36K3W5C2R0A3M8N9P7W.json",
    }
    return _write_entity(
        root, task_id, "work-units", work_unit, "work-unit.schema.json", "work_unit_created",
        expected_revision=0, idempotency_key="work-unit", actor="proposer",
    )


def test_spoofed_owner_flag_without_trusted_context_cannot_approve_scope(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    _repo(tmp_path)
    _use_repo_schemas(tmp_path, monkeypatch)
    task_id = _task(tmp_path)

    completed = _run_cli(
        tmp_path,
        "scope", "approve", task_id,
        "--actor", "backend-owner",
        "--expected-revision", "0",
        "--idempotency-key", "spoofed-approval",
    )

    assert completed.exit_code != 0
    assert completed.exception.code == "EXTERNAL_AUTHORITY_REQUIRED"
    assert not list((tmp_path / "tasks" / task_id / "approvals").glob("*.json"))


def test_self_reported_l2_runtime_flags_cannot_create_attested_run(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    _repo(tmp_path)
    _use_repo_schemas(tmp_path, monkeypatch)
    task_id = _task(tmp_path)
    _ready_work_unit(tmp_path, task_id)

    completed = _run_cli(
        tmp_path,
        "run", "register", task_id,
        "--work-unit-id", WORK_UNIT_ID,
        "--profile", "local-single",
        "--context-id", "forged-context",
        "--actor", "forged-reviewer",
        "--independence-level", "L2",
        "--provider", "other-runtime",
        "--model", "review-model",
        "--read-only",
        "--expected-revision", "1",
        "--idempotency-key", "forged-l2",
    )

    assert completed.exit_code != 0
    assert completed.exception.code == "PROVENANCE_UNVERIFIED"
    assert not list((tmp_path / "tasks" / task_id / "runs").glob("*.json"))


def test_verified_application_scope_approval_is_event_first_and_redacted(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    _repo(tmp_path)
    _use_repo_schemas(tmp_path, monkeypatch)
    task_id = _task(tmp_path)
    context = _authority()

    result = record_verified_scope_approval(
        tmp_path,
        task_id,
        declared_actor="backend-owner",
        independence_level="L1",
        expected_revision=0,
        idempotency_key="verified-approval",
        authority_context=context,
    )

    event = result["event"]
    assert event["new_revision"] == 1
    assert load_data(tmp_path / "tasks" / task_id / "task.yaml")["revision"] == 1
    assert load_data(tmp_path / "tasks" / task_id / "scope-contract.yaml")["status"] == "approved"
    assert (event["payload"] or {})["verified_authority"] == {
        "actor_id": "backend-owner",
        "source": "test-external-verifier",
        "assertion_digest": context.assertion_digest,
    }
    event_text = (tmp_path / "tasks" / task_id / "events" / f"{event['event_id']}.json").read_text(encoding="utf-8")
    assert "raw_credential" not in event_text and "must-not-persist" not in event_text
    assert verified_entity_ids([event], "approval_id") == {result["approval"]["id"]}
    assert "CLOSE_SCOPE_APPROVAL_INVALID" not in evaluate_repository_close(
        tmp_path, task_id, "backend-owner",
    ).codes


def test_declared_actor_conflicting_with_verified_context_is_rejected_before_write(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    _repo(tmp_path)
    _use_repo_schemas(tmp_path, monkeypatch)
    task_id = _task(tmp_path)

    with pytest.raises(MacError) as caught:
        record_verified_scope_approval(
            tmp_path,
            task_id,
            declared_actor="backend-owner",
            independence_level="L1",
            expected_revision=0,
            idempotency_key="conflict",
            authority_context=_authority("different-agent"),
        )

    assert caught.value.code == "ACTOR_CONTEXT_MISMATCH"
    assert len(FilesystemTaskRepository(tmp_path).list_events(task_id)) == 1


def test_l1_cli_run_is_stored_as_declaration_and_cannot_be_promoted_to_l2(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    _repo(tmp_path)
    _use_repo_schemas(tmp_path, monkeypatch)
    task_id = _task(tmp_path)
    _ready_work_unit(tmp_path, task_id)

    completed = _run_cli(
        tmp_path,
        "run", "register", task_id,
        "--work-unit-id", WORK_UNIT_ID,
        "--context-id", "declared-context",
        "--actor", "declared-reviewer",
        "--independence-level", "L1",
        "--expected-revision", "1",
        "--idempotency-key", "declared-l1",
    )

    assert completed.exit_code == 0, completed.exception
    run = json.loads(completed.stdout)["run"]
    assert set(run["runtime"]) == {"profile", "execution_context_id"}
    assert "independence_attestation" not in run
    persisted = {**run, "status": "succeeded"}
    review = {
        "kind": "review",
        "run_id": run["id"],
        "review": {"independence_level": "L2", "reviewed_diff_digest": "sha256:" + "a" * 64},
    }
    decision = evaluate_review_independence(
        review,
        persisted,
        [],
        current_diff_digest="sha256:" + "a" * 64,
        minimum_level="L2",
        runtime_profiles={"local-single": {"capabilities": {"read_only_run": "native"}}},
        verified_run_ids=set(),
    )
    assert {"REVIEW_LEVEL_UNATTESTED", "REVIEW_PROVENANCE_UNVERIFIED"} <= set(decision.codes)


def test_verified_l2_run_event_is_traceable_and_direct_spoof_is_rejected(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    _repo(tmp_path)
    _use_repo_schemas(tmp_path, monkeypatch)
    task_id = _task(tmp_path)
    work_unit = _ready_work_unit(tmp_path, task_id)
    runtime = {
        "profile": "local-single",
        "execution_context_id": "verified-review-context",
        "provider": "external-runtime",
        "model": "review-model",
        "read_only": True,
        "commit_participation": [],
    }
    context = _authority("verified-reviewer", runtime=runtime)
    fields = resolve_run_registration(
        frozen_profile_id="local-single",
        declared_profile="local-single",
        declared_context_id="verified-review-context",
        declared_actor="verified-reviewer",
        declared_actor_kind="agent",
        declared_independence_level="L2",
        declared_provider="external-runtime",
        declared_model="review-model",
        declared_read_only=True,
        declared_commit_participation=[],
        authority_context=context,
    )
    run_id = "RUN-01K0W4Z36K3W5C2R0A3M8N9P7T"
    run = {
        "schema_version": 1, "id": run_id, "task_id": task_id, "work_unit_id": WORK_UNIT_ID,
        "status": "running", **fields, "started_at": "2026-07-20T00:00:00Z",
        "finished_at": None, "exit_code": None,
    }
    repository = FilesystemTaskRepository(tmp_path)
    run_path = repository.task_dir(task_id) / "runs" / f"{run_id}.json"
    event = repository.append_event(
        task_id, "run_started", {"run_id": run_id, "run": run, "work_unit_id": WORK_UNIT_ID, "work_unit": work_unit},
        actor=context.actor(), expected_revision=1, idempotency_key="verified-run", run_id=run_id,
        materializations=[(run_path, run)], authority_context=context,
    ).event
    assert verified_entity_ids([event], "run_id") == {run_id}

    spoof_id = "RUN-01K0W4Z36K3W5C2R0A3M8N9P7V"
    spoof = {**run, "id": spoof_id}
    with pytest.raises(MacError) as caught:
        repository.append_event(
            task_id, "run_started", {"run_id": spoof_id, "run": spoof},
            actor=spoof["actor"], expected_revision=2, idempotency_key="spoofed-run",
            materializations=[(repository.task_dir(task_id) / "runs" / f"{spoof_id}.json", spoof)],
        )
    assert caught.value.code == "PROVENANCE_UNVERIFIED"
    assert not (repository.task_dir(task_id) / "runs" / f"{spoof_id}.json").exists()


def test_direct_privileged_event_and_historical_self_reported_approval_fail_closed(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch,
) -> None:
    _repo(tmp_path)
    _use_repo_schemas(tmp_path, monkeypatch)
    task_id = _task(tmp_path)
    repository = FilesystemTaskRepository(tmp_path)
    with pytest.raises(TypeError):
        VerifiedAuthorityContext(
            "backend-owner", "human", "forged", "sha256:" + "0" * 64,
        )
    with pytest.raises(MacError) as caught:
        repository.append_event(
            task_id, "scope_approved", {"approval_id": "APR-01K0W4Z36K3W5C2R0A3M8N9P81"},
            actor={"id": "backend-owner", "kind": "human"}, expected_revision=0,
            idempotency_key="direct-spoof",
        )
    assert caught.value.code == "EXTERNAL_AUTHORITY_REQUIRED"

    task_dir = repository.task_dir(task_id)
    scope = load_data(task_dir / "scope-contract.yaml")
    scope["status"] = "approved"
    scope["approved_by"] = ["backend-owner"]
    atomic_write_yaml(task_dir / "scope-contract.yaml", scope)
    approval = {
        "schema_version": 1, "id": "APR-01K0W4Z36K3W5C2R0A3M8N9P81", "task_id": task_id,
        "kind": "scope", "actor": {"id": "backend-owner", "kind": "human"},
        "decision": "approved", "subject_ref": f"tasks/{task_id}/scope-contract.yaml",
        "independence_level": "L1", "recorded_at": "2026-07-20T00:00:00Z",
    }
    atomic_write_json(task_dir / "approvals" / f"{approval['id']}.json", approval)
    decision = evaluate_repository_close(tmp_path, task_id, "backend-owner")
    assert "CLOSE_SCOPE_APPROVAL_INVALID" in decision.codes
